# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'pub_date')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'update time')),
                ('content_raw', models.TextField()),
                ('content', models.TextField(blank=True, default=b'', null=True)),
                ('click', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
